apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: siam-attai
  namespace: ingress-basic
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: siam-attai
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
